method: texnet
inherit_from: configs/singleview/texfields/chair.yaml
data:
  path_shapes: data/shapenet/chairs3dgen
  dataset_imgs_type: image_folder
  img_size: 256
  loc: [48, 48, 48]
  scale: 96
generation:
  batch_size: 1
test:
  model_file: model_best.pt
  vis_dir: 'out/vis/chairs'
  dataset_split: 'test_vis'
  with_occnet: False
  generation_mode: 'HD'
