method: texnet
data:
  path_shapes: data/matterport/processed/
  dataset_imgs_type: image_folder
  camera_mode: matterport
  sdf_path: data/matterport/processed/sdf
  img_format: jpg
  input_img_format: jpg
  img_size: 128
  depth_format: png
training:
  out_dir: 'out/singleview/matterport'
  batch_size: 6
  model_selection_metric: loss_val
  model_selection_mode: minimize
  print_every: 100
  visualize_every: 5000
  checkpoint_every: 20000
  validate_every: 50000
  backup_every: 100000
  moving_average_beta: 0
  pc_subsampling: 2048
  vis_fixviews: True
  weight_pixelloss: 1.
  weight_ganloss: 0.
  experiment: 'conditional'
  gradient_penalties_reg: 0.
model:
  decoder: each_layer_c_larger
  encoder: resnet18
  geometry_encoder: resnet
  decoder_kwargs:
    leaky: True
    resnet_leaky: False
  encoder_kwargs: {}
  geometry_encoder_kwargs: {}
  generator_bg_kwargs: {}
  discriminator_kwargs: {}
  z_dim: 512
  c_dim: 512
  white_bg: False
  model_url:
generation:
  batch_size: 1
test:
  model_file: model_best.pt
  vis_dir: 'out/singleview/matterport/eval_fix/'
  dataset_split: 'test_vis' 
  with_occnet: False
  generation_mode: 'HD'
