method: texnet
inherit_from: configs/singleview/texfields/matterport.yaml
data:
  path_shapes: data/matterport/test_32/
  path_mesh: /mnt/raid/yawar/tmp_results/ours_chunks_32
  dataset_imgs_type: image_folder
  img_size: 256
  loc: [48, 48, 48]
  scale: 96
generation:
  batch_size: 1
test:
  model_file: model_best.pt
  vis_dir: 'out/vis/matterport_32_ourgeo'
  dataset_split: 'test_vis'
  with_occnet: False
  generation_mode: 'HD'
